<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "{{%students}}".
 *
 * @property string $id
 * @property string $name 姓名
 * @property int $sex 性别
 * @property string $hobby 爱好
 *
 * @property Grade[] $grades
 */
class Students extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%students}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['sex'], 'integer'],
            [['name', 'hobby'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', '姓名'),
            'sex' => Yii::t('app', '性别'),
            'hobby' => Yii::t('app', '爱好'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGrades()
    {
        return $this->hasMany(Grade::className(), ['student_id' => 'id']);
    }

    /**
     * {@inheritdoc}
     * @return StudentsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new StudentsQuery(get_called_class());
    }

    public  function  beforeSave($insert)
    {
//	    return parent::beforeSave($insert); // TODO: Change the autogenerated stub
	    if($this->sex === null) $this->sex = 1;
	    if(!parent::beforeSave($insert)){
	    	return false;
	    }
	    return true;
    }

    public  static  function  getSex($sex=null)
    {

    	$arr = [
    		0 => '女',
		    1 => '男'
	    ];
	    if ($sex !== null) return $arr[$sex];
    	//if (isset($sex)) return $arr[$sex];
    	return $arr;
    }
}
