<?php

namespace app\models;

use app\common\helpers\ArrayHelper;
use cebe\markdown\tests\ParserTest;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "{{%subject}}".
 *
 * @property int $id
 * @property string $name 学科
 * @property int $status 状态
 *
 * @property Grade[] $grades
 */
class Subject extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%subject}}';
    }

    public function behaviors()
    {
//	    return parent::behaviors(); // TODO: Change the autogenerated stub
	    return ArrayHelper::merge(parent::behaviors(), [
		    [
			    'class' => TimestampBehavior::className(),
			    'attributes' => [
				    ActiveRecord::EVENT_BEFORE_INSERT => ['create_at', 'update_at'],
				    ActiveRecord::EVENT_BEFORE_UPDATE => ['update_at'],
			    ],
			    // if you're using datetime instead of UNIX timestamp:
//			     'value' => 222 //( 这也可以)
		    ],
		]);
    }

	/**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['status','create_at','update_at'], 'integer'],
            [['name'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', '学科'),
            'status' => Yii::t('app', '状态'),
	        'create_at' => Yii::t('app', '增加时间'),
	        'update_at' => Yii::t('app', '修改时间'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGrades()
    {
        return $this->hasMany(Grade::className(), ['subject_id' => 'id']);
    }

    /**
     * {@inheritdoc}
     * @return SubjectQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new SubjectQuery(get_called_class());
    }

    public  static  function  getStatus($status = null){
	    $arr =  [
		    1 => '激活',
		    0 => '禁用'
	    ];
    	if($status !== null){
    		return $arr[$status];
	    }
	    return $arr;
    }
}
